require("per.set")
require("per.remap")
require("per.packer")
require("per.treesitter")
require("per.lsp")
require("per.autocomplete")
require("per.gitsigns")
require("per.rustlsp")
require("per.nvimautopairs")
require("per.feline")
require("per.color")
require("per.nvimtree")
require("per.masonlsp")
-- require("per.statusline")
